name: Build and Release

on:
  release:
    types: [created]

jobs:
  build-and-release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
    - name: Build project
      run: make build
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'release'
      with:
        files: |
            ../executables/mock-telegram-linux-x86_64
        